# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np

arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)

arr1[:,2:3] = 1
print("Array: \n",arr1)


[[15  1 19  7  8]
 [ 6 16  4  2  6]
 [ 8  5  2 18 12]
 [ 1 17 12 17  5]
 [ 8 20 17 17 12]]
Array: 
 [[15  1  1  7  8]
 [ 6 16  1  2  6]
 [ 8  5  1 18 12]
 [ 1 17  1 17  5]
 [ 8 20  1 17 12]]


In [3]:
## 2. Create a NumPy array of shape (4, 4) with values 
# from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.random.randint(1,17,size=(4,4))
print(arr2)

np.fill_diagonal(arr2,0)
print(arr2)

[[16  8  1  8]
 [ 7 11  7  6]
 [15  8  6  3]
 [15 10 15 11]]
[[ 0  8  1  8]
 [ 7  0  7  6]
 [15  8  0  3]
 [15 10 15  0]]


### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr3 = np.random.randint(1,37,size=(6,6))
print(arr3)

print(arr3[3:6,2:5])



[[13 18 19 20 17 26]
 [11 31 11 30 30  7]
 [13  3 13  7  6  4]
 [22 19 14 30 27 32]
 [24 16 14  7 11 19]
 [25  3  4  1 11 25]]
[[14 30 27]
 [14  7 11]
 [ 4  1 11]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr4 = np.random.randint(1,100,size=(5,5))
print(arr4)

modify_arr = np.copy(arr4)
modify_arr[1:-1,1:-1] = 0
print(modify_arr)

border_elements = []
border_elements.append(modify_arr[(modify_arr>0)])
print(border_elements)

[[40 23 46 12 16]
 [21 64 25 30 75]
 [ 3 29  3 94 79]
 [ 8 46 67 93 66]
 [79 53 45 44 38]]
[[40 23 46 12 16]
 [21  0  0  0 75]
 [ 3  0  0  0 79]
 [ 8  0  0  0 66]
 [79 53 45 44 38]]
[array([40, 23, 46, 12, 16, 21, 75,  3, 79,  8, 66, 79, 53, 45, 44, 38])]


In [6]:
print("Top row:",arr4[0,:])
print("Bottom row",arr4[-1,:]) # 4 can be replaced in place of -1
print("Left Column:",arr4[1:-1,0])
print("Right Column:",arr4[1:-1,-1])

Top row: [40 23 46 12 16]
Bottom row [79 53 45 44 38]
Left Column: [21  3  8]
Right Column: [75 79 66]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
arr3_1 =np.random.randint(1,10,size = (3,4))
arr3_2 =np.random.randint(1,10,size = (3,4))
print(arr3_1,"\n",arr3_2)

print("Addition: \n",arr3_2+arr3_1)
print("Substraction: \n",arr3_2-arr3_1)
print("Multiplication: \n",arr3_2*arr3_1)
print("Divisio: \n",arr3_2/arr3_1)

[[3 6 3 1]
 [3 8 9 6]
 [2 4 7 4]] 
 [[4 6 7 7]
 [1 9 7 8]
 [8 6 6 5]]
Addition: 
 [[ 7 12 10  8]
 [ 4 17 16 14]
 [10 10 13  9]]
Substraction: 
 [[ 1  0  4  6]
 [-2  1 -2  2]
 [ 6  2 -1  1]]
Multiplication: 
 [[12 36 21  7]
 [ 3 72 63 48]
 [16 24 42 20]]
Divisio: 
 [[1.33333333 1.         2.33333333 7.        ]
 [0.33333333 1.125      0.77777778 1.33333333]
 [4.         1.5        0.85714286 1.25      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [9]:
arr3_2_1 =np.random.randint(1,17,size = (4,4))
print(arr3_2_1)
row_sum = np.sum(arr3_2_1, axis=1)
print("\nRow-wise sum:", row_sum)
col_sum = np.sum(arr3_2_1, axis=0)
print("\nColumn-wise sum:", col_sum)

[[12 13  1  1]
 [13  7 15  9]
 [ 3  6  8  2]
 [ 2  9  7  9]]

Row-wise sum: [27 44 19 27]

Column-wise sum: [30 35 31 21]
